language: node_js
node_js:
  - stable
sudo: false
branches:
  only:
  - master
  - /^greenkeeper/.*$/
before_install:
  - npm i -g now greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
  - ./build.sh
